version: '3'
services:
  mysqldb:
     image: mysql/mysql-server:latest
     container_name: mysql01
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: abc123
       MYSQL_DATABASE: shoutbook